app/controllers/gains/PolicySummaryController.scala, app/views/pages/gains/CustomerReferencePageView.scala.html, app/views/pages/gains/GainsDeficiencyReliefPageView.scala.html, app/views/pages/gains/PolicyEventPageView.scala.html, app/views/pages/gains/PolicySummaryPageView.scala.html, conf/app.routes, conf/messages, conf/messages.cy, it/controllers/gains/PolicySummaryControllerISpec.scala, project/build.properties, test/views/pages/gains/DeficiencyReliefPageViewSpec.scala, test/views/pages/gains/PolicySummaryPageViewSpec.scala
=> Sass 3524 Policy summary page

app/config/AppConfig.scala, app/connectors/GainsSubmissionConnector.scala, app/connectors/Parser.scala, app/connectors/RawResponseReads.scala, app/connectors/httpParsers/GainsSubmissionHttpParser.scala, app/models/gains/CapitalRedemptionModel.scala, app/models/gains/ForeignModel.scala, app/models/gains/GainsSubmissionModel.scala, app/models/gains/LifeAnnuityModel.scala, app/models/gains/LifeInsuranceModel.scala, app/models/gains/VoidedIsaModel.scala, app/services/GainsSubmissionService.scala, app/utils/PagerDutyHelper.scala, it/connectors/GainsSubmissionConnectorISpec.scala, it/support/IntegrationTest.scala, test/connectors/ParserSpec.scala, test/models/gains/GainsSubmissionModelSpec.scala, test/services/GainsSubmissionServiceSpec.scala, test/support/helpers/WireMockServer.scala
[SASS-3960](https://jira.tools.tax.service.gov.uk/browse/SASS-3960)
=> SASS-3960 Create submission service in add-info-frontend

app/controllers/gains/PoliciesAddController.scala, app/views/pages/gains/PoliciesAddPageView.scala.html, conf/app.routes, conf/messages, conf/messages.cy, it/controllers/gains/PoliciesAddControllerISpec.scala, project/plugins.sbt, test/views/pages/gains/PoliciesAddPageViewSpec.scala
=> SASS-3525 policy add

app/views/pages/gains/PoliciesRemovePageView.scala.html, conf/messages, conf/messages.cy
=> SASS-4167 policy remove

app/views/pages/gains/GainsAmountPageView.scala.html, conf/messages, conf/messages.cy, test/views/pages/gains/GainsAmountPageViewSpec.scala
- [ x  Have you run the tests?
=> SASS-4425 Amend Gains amount page

app/controllers/gains/PaidTaxAmountController.scala, app/views/pages/gains/PaidTaxAmountPageView.scala.html, conf/app.routes, conf/messages, conf/messages.cy, it/controllers/gains/PaidTaxAmountControllerISpec.scala, test/views/pages/gains/PaidTaxAmountPageViewSpec.scala
Create "How much tax did you pay on your gain?" page - Gains from life insurance policies and contracts
SASS-4361
=> SASS-4361 Create How much tax did you pay on your gain page

app/controllers/gains/PolicyEventController.scala, app/forms/gains/RadioButtonPolicyEventForm.scala, conf/messages, conf/messages.cy, test/forms/gains/RadioButtonPolicyEventFormSpec.scala
Amend "What caused this gain?" page - Gains from life insurance policies and contracts
SASS-4349 https://jira.tools.tax.service.gov.uk/browse/SASS-4349
=> SASS-4349 Amend What caused this gain page?

conf/messages, conf/messages.cy, test/views/pages/gains/CustomerReferencePageViewSpec.scala
SASS-4620  https://jira.tools.tax.service.gov.uk/browse/SASS-4620
=> SASS-4620 Amend Policy number page

app/views/pages/gains/PolicyTypePageView.scala.html, app/views/templates/helpers/Details.scala.html, conf/messages, conf/messages.cy, test/forms/gains/InputFieldFormSpec.scala, test/views/pages/gains/PolicyTypePageViewSpec.scala
[SASS-4619](https://jira.tools.tax.service.gov.uk/browse/SASS-4619)
=> SASS-4619 Amend policy type page

app/views/pages/gains/GainsDeficiencyReliefPageView.scala.html, conf/messages, test/views/pages/gains/GainsGatewayPageViewSpec.scala
[SASS-4983] (https://jira.tools.tax.service.gov.uk/browse/SASS-4983)
=> SASS-4983 Amend welsh content

build.sbt, conf/application.conf, project/AppDependencies.scala
=> dependency updates

app/connectors/GetGainsConnector.scala, app/connectors/Parser.scala, app/models/gains/prior/GainsPriorDataModel.scala, conf/application.conf, it/connectors/GetGainsConnectorISpec.scala, it/connectors/NrsConnectorSpec.scala, it/controllers/gains/GainsStatusControllerISpec.scala, it/controllers/gains/PolicyNameControllerISpec.scala, it/controllers/gains/PolicySummaryControllerISpec.scala, it/repositories/UserDataRepositoryISpec.scala, it/services/GainsSessionServiceISpec.scala, it/support/IntegrationTest.scala, test/audit/CreateOrAmendGainsAuditDetailSpec.scala, test/models/gains/prior/GainsPriorDataModelSpec.scala, test/services/NrsServiceSpec.scala
Added pagerDutyLogger to APIParser, changed url for GET call, updated model to match API spec.
=> fixes for logging, url and model

app/controllers/gains/GainsGatewayController.scala, app/models/AllGainsSessionModel.scala, app/models/gains/GainsSubmissionModel.scala, app/services/GainsSubmissionService.scala, it/connectors/GainsSubmissionConnectorISpec.scala, it/connectors/NrsConnectorSpec.scala, it/controllers/gains/GainsGatewayControllerISpec.scala, test/audit/CreateOrAmendGainsAuditDetailSpec.scala, test/models/gains/GainsSubmissionModelSpec.scala, test/services/GainsSubmissionServiceSpec.scala, test/services/NrsServiceSpec.scala
=> edit submission model

conf/application.conf, project/AppDependencies.scala, project/plugins.sbt
Additional Information: Deprecated Application Security Header.
[SASS-5357](https://jira.tools.tax.service.gov.uk/browse/SASS-5377)
=> SASS-5357 Additional Information: Deprecated Application Security Header

app/views/pages/gains/GainsStatusPageView.scala.html, app/views/pages/gains/PaidTaxStatusPageView.scala.html
=> SASS-5434 Accessibility fix missing legend text

app/forms/gains/InputFieldForm.scala, app/forms/validation/mappings/MappingUtil.scala
=> SASS-5440 Accessibility fix validation accomodate spaces

app/controllers/gains/GainsGatewayController.scala, app/views/pages/gains/GainsGatewayPageView.scala.html, conf/app.routes, it/controllers/gains/GainsGatewayControllerISpec.scala, project/AppDependencies.scala
Fixes the toggle when used with a form error on the gateway page.
[SASS-5438](https://jira.tools.tax.service.gov.uk/browse/SASS-5438)
=> SASS-5438: Issue: Welsh language toggle not working

app/controllers/gains/PolicySummaryController.scala, project/AppDependencies.scala, project/plugins.sbt
[SASS-5577](https://jira.tools.tax.service.gov.uk/browse/SASS-5577)
=> SASS-5577 Update audit events for gains

app/audit/CreateOrAmendGainsAuditDetail.scala, app/controllers/gains/PolicySummaryController.scala, app/models/AllGainsSessionModel.scala, app/models/gains/GainsSubmissionModel.scala, app/models/gains/VoidedIsaModel.scala, app/models/gains/prior/GainsPriorDataModel.scala, conf/application.conf, conf/prod.routes, project/AppDependencies.scala, project/build.properties, project/plugins.sbt, test/audit/CreateOrAmendGainsAuditDetailSpec.scala, test/models/gains/prior/GainsPriorDataModelSpec.scala
=> update audit content

app/controllers/gains/GainsSummaryController.scala, app/models/gains/VoidedIsaModel.scala, app/models/gains/prior/GainsPriorDataModel.scala, app/services/GainsSessionService.scala, it/controllers/gains/GainsSummaryControllerISpec.scala, it/support/IntegrationTest.scala, test/models/gains/prior/GainsPriorDataModelSpec.scala
=> SASS-5509: Check and update configs - Additional information frontend

app/connectors/httpParsers/GainsSubmissionHttpParser.scala, app/controllers/gains/PolicyNameController.scala, app/controllers/gains/PolicySummaryController.scala, app/forms/validation/StringConstraints.scala, app/models/AllGainsSessionModel.scala, app/services/GainsSubmissionService.scala, it/connectors/GainsSubmissionConnectorISpec.scala, it/controllers/gains/PolicySummaryControllerISpec.scala, project/plugins.sbt, test/forms/gains/InputFieldFormSpec.scala, test/forms/validation/StringConstraintsSpec.scala, test/views/pages/gains/PolicyNamePageViewSpec.scala
=> SASS-6664 Gains update summary page behaviour to include prior data

app/controllers/gains/GainsSummaryController.scala, app/services/GainsSessionService.scala, app/utils/HMRCHeaderNames.scala, it/support/IntegrationTest.scala
=> SASS-6664 Added additional logs

app/models/gains/prior/GainsPriorDataModel.scala
=> SASS-6664 Updated prior data model

app/views/pages/gains/PolicyNamePageView.scala.html, conf/messages, conf/messages.cy, test/views/pages/gains/PolicyNamePageViewSpec.scala
=> SASS-7322 Updated content changes for policy name page

project/AppDependencies.scala
=> SASS-7337 Updated play frontend library version for tudor crown change

app/controllers/gains/PolicySummaryController.scala, app/views/pages/gains/PolicyTypePageView.scala.html, it/controllers/gains/PolicySummaryControllerISpec.scala, test/models/AllGainsSessionModelSpec.scala, test/models/gains/prior/GainsPriorDataModelSpec.scala
=> SASS-6664 submit policy data along with prior data

app/controllers/gains/PolicySummaryController.scala
=> SASS-6664 Update policy submission

app/controllers/gains/PoliciesRemoveController.scala, app/controllers/gains/PolicySummaryController.scala
update audit transaction name format
=> SASS-7472: update audit transaction name format

app/models/gains/CapitalRedemptionModel.scala, app/models/gains/ForeignModel.scala, app/models/gains/LifeAnnuityModel.scala, app/models/gains/LifeInsuranceModel.scala, app/models/gains/PolicyCyaModel.scala, app/models/gains/VoidedIsaModel.scala, test/models/gains/prior/GainsPriorDataModelSpec.scala
Update models so redirection works correctly, refactor isFinished function.
=> Sass 7464: update life insurance policy models

app/views/pages/gains/PolicyTypePageView.scala.html, project/AppDependencies.scala, test/views/pages/gains/PolicyTypePageViewSpec.scala
=> SASS-10197: Fix multiple h1 on a page

app/views/pages/gains/PolicyEventPageView.scala.html, test/views/pages/gains/PolicyEventPageViewSpec.scala
=> SASS-10241 | DAC Issue: Incorrect copy for legend (A)

app/views/pages/gains/PaidTaxAmountPageView.scala.html
Work linked to main ticket - SASS-8921
=> SASS-10238: Updated message key for label to rendered correctly

app/actions/AuthorisedAction.scala, app/config/AppConfig.scala, conf/application.conf, test/actions/AuthorisedActionSpec.scala, test/support/mocks/MockAuthConnector.scala, test/support/stubs/AppConfigStub.scala
=> EMA changes - Added logic to deal with primary and supporting agent.

app/views/pages/gains/PolicyHeldPageView.scala.html, check.sh, project/AppDependencies.scala, project/plugins.sbt, test/views/pages/gains/PolicyHeldPageViewSpec.scala
=> SASS-10713 Refactor copy text into Hint and update tests

app/actions/AuthorisedAction.scala, test/actions/AuthorisedActionSpec.scala, test/support/mocks/MockAuthorisedAction.scala, test/support/mocks/MockAuthorisedActionCIS.scala
=> SASS-10751 Use ErrorHandler to render ISE page

app/forms/gains/InputFieldForm.scala, app/forms/validation/StringConstraints.scala, app/forms/validation/mappings/MappingUtil.scala, test/forms/gains/InputFieldFormSpec.scala, test/forms/validation/StringConstraintsSpec.scala, test/views/pages/gains/PolicyNamePageViewSpec.scala
- Updated regex to accept '/'
- Set code to replace all '/' with '-'
- Added new unit tests to accommodate change
=> SASS-10947: Accommodating '/' policy number

app/views/pages/businessReliefs/BusinessReliefsNonDeductiblePageView.scala.html, conf/messages, conf/messages.cy, test/fixtures/messages/businessTaxReliefs/BusinessReliefsNonDeductibleMessages.scala, test/views/pages/businessTaxReliefs/BusinessReliefsNonDeductiblePageViewSpec.scala
=> SASS-11419: Updated publications link new tab

app/controllers/businessTaxReliefs/BusinessReliefsQualifyingLoanController.scala, app/controllers/businessTaxReliefs/CheckAnswersQualifyingLoanController.scala, app/viewmodels/businessTaxReliefs/CheckAnswersQualifyingLoanSummary.scala, app/views/pages/businessTaxReliefs/CheckAnswersQualifyingLoanPageView.scala.html, conf/app.routes, conf/messages, conf/messages.cy, it/test/controllers/BusinessTaxReliefs/BusinessReliefsQualifyingLoanControllerISpec.scala, it/test/controllers/BusinessTaxReliefs/CheckAnswersQualifyingLoanControllerISpec.scala, test/fixtures/messages/businessTaxReliefs/BusinessReliefsQualifyingLoanMessages.scala, test/fixtures/messages/i18n.scala, test/viewmodels/businessTaxReliefs/CheckAnswersQualifyingLoanSummarySpec.scala, test/views/pages/businessTaxReliefs/BusinessReliefsQualifyingLoanPageViewSpec.scala, test/views/pages/businessTaxReliefs/CheckAnswersQualifyingLoanPageViewSpec.scala, test/views/utils/BaseSelectors.scala
**Description**
Adds the Check Answers Qualifying Loan Interest page
**JT**
- https://github.com/hmrc/income-tax-submission-journey-tests/pull/558
**PT**
- https://github.com/hmrc/income-tax-submission-performance-tests/pull/160
=> [SASS-11423] Add CYA page for Qualifying Loan Interest

app/config/Module.scala, app/connectors/ConnectorConfig.scala, app/connectors/Parser.scala, app/connectors/httpParsers/UserSessionDataHttpReads.scala, app/connectors/session/UserSessionDataConnector.scala, app/models/session/UserSessionData.scala, app/utils/ConfigLoaderProvider.scala, app/utils/PagerDutyHelper.scala, build.sbt, conf/application.conf, it/test/connectors/TestConnectorConfig.scala, it/test/connectors/session/UserSessionDataConnectorISpec.scala, test/support/helpers/WireMockServer.scala
=> SASS-11581 Add connector to income-tax-session-data µService

conf/application.conf
=> SASS-11666
